artifact_location: /Users/caffretro/Ca2+/HKU/HKU-Smart-Mobility-Lab/Reproductions/KSTDiff-Urban-flow-generation/mlflow_output/295948468489252820
creation_time: 1760064462451
experiment_id: '295948468489252820'
last_update_time: 1760064462451
lifecycle_stage: active
name: TuckER_pretrain
