artifact_uri: /Users/caffretro/Ca2+/HKU/HKU-Smart-Mobility-Lab/Reproductions/KSTDiff-Urban-flow-generation/mlflow_output/295948468489252820/04cce0ff64994d6dac8746cae76511bf/artifacts
end_time: 1760064462851
entry_point_name: ''
experiment_id: '295948468489252820'
lifecycle_stage: active
run_id: 04cce0ff64994d6dac8746cae76511bf
run_name: lyrical-gull-802
source_name: ''
source_type: 4
source_version: ''
start_time: 1760064462552
status: 4
tags: []
user_id: caffretro
